[package]
name = "transport-usb"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
transport-api = { path = "../transport-api" }

[target.'cfg(target_os = "linux")'.dependencies]
rusb = { version = "0.9.4", features = ["vendored"] }

[lints]
workspace = true

