[package]
name = "aa-headunit-diagnostics"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
platform-api = { path = "../../crates/platform-api" }
platform-linux = { path = "../../crates/platform-linux" }
transport-api = { path = "../../crates/transport-api" }
transport-usb = { path = "../../crates/transport-usb" }

[lints]
workspace = true

