[package]
name = "aa-headunit-diagnostics"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
media-api = { path = "../../crates/media-api" }
media-gstreamer = { path = "../../crates/media-gstreamer" }
platform-api = { path = "../../crates/platform-api" }
platform-linux = { path = "../../crates/platform-linux" }
transport-api = { path = "../../crates/transport-api" }
transport-tcp = { path = "../../crates/transport-tcp" }
transport-usb = { path = "../../crates/transport-usb" }

[target.'cfg(target_os = "linux")'.dependencies]
credential-store = { path = "../../crates/credential-store" }
ctrlc = "3"
gtk4 = "0.10.3"
protocol-aap = { path = "../../crates/protocol-aap" }
security-openssl = { path = "../../crates/security-openssl" }
transport-bluetooth = { version = "0.1.0", path = "../../crates/transport-bluetooth" }

[lints]
workspace = true
